namespace :coverage do
  desc "Collates all result sets generated by the different test runners"
  task :report do
    require 'simplecov'
    require 'json'

    SimpleCov.load_profile 'rails'

    results = []

    Dir[Rails.root.join("resultset.*.json")].each do |file|
      JSON.parse(File.read(file)).each do |name, result_set|
        results << SimpleCov::Result.from_hash({ name => result_set })
      end
    end

    result = SimpleCov::ResultMerger.merge_results(*results)
    result.format!
    SimpleCov::ResultMerger.store_result(result)
  end
end
