FROM ruby:2.7

# ENV POIROT_STDOUT true
# ENV POIROT_SUPPRESS_RAILS_LOG true
# ENV NNDD_VERSION "cdx-0.11-pre7"

# Download NNDD
# RUN \
#   mkdir -p /app/public/ && \
#   curl -L https://github.com/instedd/notifiable-diseases/releases/download/$NNDD_VERSION/nndd.tar.gz | tar -xzv -C /app/public/


# PhantomJS
ENV PHANTOM_JS_VERSION "phantomjs-1.9.8-linux-x86_64"
ENV PHANTOM_JS_DOWNLOAD "https://bitbucket.org/ariya/phantomjs/downloads/${PHANTOM_JS_VERSION}.tar.bz2"
ENV PHANTOM_JS_TMP "/tmp/phantomjs"
ENV LOCAL_SHARE "/usr/local/share"

RUN \
  apt-get update && \
  apt-get install -y \
    build-essential \
    chrpath \
    libssl-dev \
    libxft-dev \
    libfreetype6 \
    libfreetype6-dev \
    libfontconfig1 \
    libfontconfig1-dev \
    libv8-dev \
    # wkhtmltopdf dependencies \
    xfonts-75dpi \
    xfonts-base \
  && apt-get clean && rm -rf /var/lib/apt/lists/* /tmp/* /var/tmp/*

RUN \
  mkdir ${PHANTOM_JS_TMP} && \
  cd ${PHANTOM_JS_TMP} && \
  curl -L ${PHANTOM_JS_DOWNLOAD} --output ${PHANTOM_JS_VERSION}.tar.bz2 && \
  tar xvjf ${PHANTOM_JS_VERSION}.tar.bz2 && \
  mv ${PHANTOM_JS_VERSION} ${LOCAL_SHARE} && \
  ln -sf ${LOCAL_SHARE}/${PHANTOM_JS_VERSION}/bin/phantomjs /usr/local/bin && \
  rm -f ${PHANTOM_JS_VERSION}.tar.bz2

# wkhtmltopdf
RUN \
  curl -L https://github.com/wkhtmltopdf/wkhtmltopdf/releases/download/0.12.5/wkhtmltox_0.12.5-1.buster_amd64.deb --output wkhtmltopdf.deb && \
  dpkg -i wkhtmltopdf.deb && \
  rm -f wkhtmltopdf.deb

RUN \
  mkdir /tmp/node && \
  cd /tmp/node && \
  wget https://nodejs.org/dist/v14.16.1/node-v14.16.1-linux-x64.tar.xz && \
  tar xvf node-v14.16.1-linux-x64.tar.xz && \
  mv node-v14.16.1-linux-x64 /usr/local/share && \
  ln -sf /usr/local/share/node-v14.16.1-linux-x64/bin/node /usr/local/bin && \
  rm -f node-v14.16.1-linux-x64.tar.xz
