FROM alpine

RUN apk add firefox-esr
RUN apk add curl

# FIXME: can't upgrade to 0.30 because Geckodriver only starts on loopback
RUN curl -L https://github.com/mozilla/geckodriver/releases/download/v0.29.1/geckodriver-v0.29.1-linux64.tar.gz | \
  tar -C /usr/local/bin -zx

RUN apk del curl

EXPOSE 4444
EXPOSE 5900

ENTRYPOINT ["geckodriver", "--host", "0.0.0.0"]
