FROM alpine

RUN echo "https://dl-cdn.alpinelinux.org/alpine/edge/community" >> /etc/apk/repositories
RUN apk add firefox-esr geckodriver
RUN ln -sf /usr/bin/firefox-esr /usr/bin/firefox

EXPOSE 4444
EXPOSE 5900
