FROM alpine

RUN apk add firefox-esr
RUN apk add curl

# FIXME: can't upgrade to 0.30 because Geckodriver only starts on loopback
RUN curl -L https://github.com/mozilla/geckodriver/releases/download/v0.29.1/geckodriver-v0.29.1-linux64.tar.gz | \
  tar -C /usr/local/bin -zx

RUN apk del curl

EXPOSE 4444
EXPOSE 5900

RUN echo "#! /usr/bin/env sh" > /entrypoint.sh && \
    echo "geckodriver --host 0.0.0.0 -p 4444 &" >> /entrypoint.sh && \
    echo "geckodriver --host 0.0.0.0 -p 4445 &" >> /entrypoint.sh && \
    echo "geckodriver --host 0.0.0.0 -p 4446 &" >> /entrypoint.sh && \
    echo "geckodriver --host 0.0.0.0 -p 4447 &" >> /entrypoint.sh && \
    echo "geckodriver --host 0.0.0.0 -p 4448 &" >> /entrypoint.sh && \
    echo "geckodriver --host 0.0.0.0 -p 4449 &" >> /entrypoint.sh && \
    echo "geckodriver --host 0.0.0.0 -p 4450 &" >> /entrypoint.sh && \
    echo "geckodriver --host 0.0.0.0 -p 4451" >> /entrypoint.sh && \
    chmod +x /entrypoint.sh

ENTRYPOINT ["/entrypoint.sh"]
